# Conditionals: `if: github.ref == 'refs/heads/main'`
name: conditional-demo

on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
 workflow_dispatch:

jobs:
  on-push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: only run on push events
        run: echo "Only run on push events"